imu_processor:
  ros__parameters:
    imu_raw_topic: "/imu/data_raw"
    mag_raw_topic: "/imu/mag"
    imu_output_topic: "/imu/data_corrected"
    imu_freq_hz: 10.0              # Coincide con Yahboom
    madgwick_beta: 0.04             # Conservador, reduce deriva
    mag_declination_rad: 0.0        # Ajusta según tu localización
    publish_imu_raw_tf: false       # Debug si es necesario