fsm_aebs_node:
  ros__parameters:
    # Geometría
    robot_width: 0.15
    chassis_length: 0.37
    lidar_yaw_offset: 0.0
    lane_margin: 0.10
    straight_turn_w_threshold: 0.05
    range_min_valid: 0.10
    
    # Seguridad
    ttc_threshold_slow: 1.0    # Banda conservadora para velocidad baja
    ttc_threshold_fast: 1.5    # Banda conservadora para velocidad alta
    min_safe_distance: 0.15    # Burbuja estática
    scan_timeout_sec: 0.5      # Frenar si el Lidar se congela 500ms
    min_motion_velocity: 0.05
    min_danger_points: 3
    
    # Mapeo Empírico (Debe coincidir con fsm_control)
    # La nueva ESC tiene oscilaciones; 0.1-0.2 es una banda útil aproximada, no un valor exacto.
    v_slow_real: 1.30
    v_fast_real: 1.40
    pwm_fast_threshold: 0.15
    pwm_deadzone: 0.08
    stop_pwm: 0.0