pure_pursuit_node:
  ros__parameters:
    path_topic: "/planned_path"
    cmd_vel_topic: "/cmd_vel_nav"
    base_frame: "base_link"
    
    control_rate_hz: 10.0
    v_nominal: 0.11
    max_speed: 0.11
    max_omega: 1.8       # Ajusta según la capacidad de giro de tu carro
    goal_tolerance: 0.1

    lookahead_L0: 0.6
    lookahead_kv: 0.163
    lookahead_min: 0.4
    lookahead_max: 2.0